#!/usr/bin/env node
//
// check-nav — every narrative post must be reachable from the sidebar nav.
//
// A post file can exist, build, and deploy while being INVISIBLE on the site,
// because it was never added to astro.config.mjs's sidebar `items`. That is
// exactly how series-007-005 and 007-006 shipped unseen: built, reachable by
// direct URL, absent from the nav. This guard makes that unconstructable.
//
// It covers BOTH narrative tracks (see scripts/lib/posts.mjs):
//   - blog/story/**   the trunk, wired post-by-post with `slug:`
//   - blog/fronts/**  the live workstream tracks, which grow weekly and are
//                     wired by `autogenerate: { directory }` so a new post
//                     needs no nav edit (STORY-BRANCHING.md §3.2, §4.2)
//
// So "wired" means EITHER an explicit `slug:` OR coverage by an autogenerate
// directory. Counting only `slug:` would fail every front post the moment the
// first one lands, and the obvious "fix" — hand-listing them — reintroduces the
// drift FM-3 records.
//
// It runs in the postbuild chain, so even the Cloudflare deploy build refuses an
// unlinked post rather than silently shipping it. Built is not linked.

import { readFile } from "node:fs/promises";
import { discoverPosts } from "./lib/posts.mjs";

const CONFIG = "astro.config.mjs";
const config = await readFile(CONFIG, "utf-8");

// Explicit leaves: `{ slug: "blog/story/..." }`
const wired = new Set(
  [...config.matchAll(/slug:\s*["\']([^"\']+)["\']/g)].map((m) => m[1]),
);

// Autogenerated groups: `autogenerate: { directory: "blog/fronts/exemplar" }`
const autoDirs = [
  ...config.matchAll(/autogenerate:\s*\{\s*directory:\s*["\']([^"\']+)["\']/g),
].map((m) => m[1].replace(/\/+$/, ""));

const covered = (slug) =>
  wired.has(slug) || autoDirs.some((d) => slug === d || slug.startsWith(`${d}/`));

const posts = await discoverPosts();
const missing = posts.filter((p) => !covered(p.slug));

if (missing.length) {
  console.error(
    `[check-nav] FAIL — ${missing.length} post(s) built but NOT reachable from the sidebar (${CONFIG}):`,
  );
  for (const m of missing) {
    console.error(`  ${m.file}`);
    if (m.kind === "front") {
      const dir = m.slug.split("/").slice(0, 3).join("/");
      console.error(`    → wire the track:  { label: "…", autogenerate: { directory: "${dir}" } },`);
      console.error(`    → or the one post: { slug: "${m.slug}" },`);
    } else {
      console.error(`    → add to a sidebar group:  { slug: "${m.slug}" },`);
    }
  }
  console.error(
    `[check-nav] a post not in the nav is invisible on the site. Wire it in, then rebuild.`,
  );
  process.exit(1);
}

// ---------------------------------------------------------------------------
// A front's landing page must sort FIRST inside its own autogenerated group.
//
// Starlight's `autogenerate` sorts a directory by `sidebar.order`, and that
// order is scoped to THAT DIRECTORY. The landing pages were first written with
// orders 1..4 meaning "which front is this" — a different question entirely —
// so every one of them sorted among, or after, its own posts. Ties break
// alphabetically, which put `001-…` above `index`. The reader met a front's
// third post before its introduction.
//
// A landing carries order 0 and everything else is >= 1. Checked, because the
// number that broke this was plausible at every single site.
// ---------------------------------------------------------------------------
const orderOf = async (file) => {
  const text = await readFile(file, "utf-8");
  const m = text.match(/sidebar:\s*\n\s*order:\s*([0-9.]+)/);
  return m ? Number(m[1]) : null;
};

// A TRACK is blog/fronts/<track> — three segments. `blog/fronts` itself is the
// overview page, not a track, and including it made every track landing look
// like a post competing with the overview.
const frontDirs = [...new Set(
  posts
    .filter((p) => p.kind === "front" && p.slug.split("/").length >= 3)
    .map((p) => p.slug.split("/").slice(0, 3).join("/")),
)].filter((d) => d.split("/").length === 3);

const orderBad = [];
for (const dir of frontDirs) {
  const inDir = posts.filter((p) => p.slug === dir || p.slug.startsWith(dir + "/"));
  const landing = inDir.find((p) => p.isLanding || p.slug === dir);
  if (!landing) continue;
  const landingOrder = await orderOf(landing.file);
  if (landingOrder === null) {
    orderBad.push({ dir, why: `landing has no sidebar.order` });
    continue;
  }
  for (const p of inDir) {
    if (p === landing) continue;
    const o = await orderOf(p.file);
    if (o === null) continue;
    if (o <= landingOrder) {
      orderBad.push({
        dir,
        why: `${p.slug.split("/").pop()} has order ${o}, landing has ${landingOrder}`,
      });
    }
  }
}

if (orderBad.length) {
  console.error(`\n[check-nav] ✗ ${orderBad.length} front landing ordering problem(s):\n`);
  for (const b of orderBad) console.error(`  ${b.dir} — ${b.why}`);
  console.error(
    `\n[check-nav] a front's landing must sort FIRST in its own autogenerated group.` +
      `\n            Give every landing 'sidebar: order: 0' and its posts 1 and up.` +
      `\n            Starlight's order is scoped to the DIRECTORY, not to the site.`,
  );
  process.exit(1);
}

const story = posts.filter((p) => p.kind === "story").length;
const front = posts.filter((p) => p.kind === "front").length;
console.error(
  `[check-nav] ✓ all ${posts.length} narrative posts are reachable (${story} story, ${front} front${autoDirs.length ? `; ${autoDirs.length} autogenerated group(s)` : ""})`,
);
