#!/usr/bin/env node
//
// check-nav — every narrative post must be reachable from the sidebar nav.
//
// A post file can exist, build, and deploy while being INVISIBLE on the site,
// because it was never added to astro.config.mjs's sidebar `items`. That is
// exactly how series-007-005 and 007-006 shipped unseen: built, reachable by
// direct URL, absent from the nav. This guard makes that unconstructable.
//
// It covers BOTH narrative tracks (see scripts/lib/posts.mjs):
//   - blog/story/**   the trunk, wired post-by-post with `slug:`
//   - blog/fronts/**  the live workstream tracks, which grow weekly and are
//                     wired by `autogenerate: { directory }` so a new post
//                     needs no nav edit (STORY-BRANCHING.md §3.2, §4.2)
//
// So "wired" means EITHER an explicit `slug:` OR coverage by an autogenerate
// directory. Counting only `slug:` would fail every front post the moment the
// first one lands, and the obvious "fix" — hand-listing them — reintroduces the
// drift FM-3 records.
//
// It runs in the postbuild chain, so even the Cloudflare deploy build refuses an
// unlinked post rather than silently shipping it. Built is not linked.

import { readFile } from "node:fs/promises";
import { discoverPosts } from "./lib/posts.mjs";

const CONFIG = "astro.config.mjs";
const config = await readFile(CONFIG, "utf-8");

// Explicit leaves: `{ slug: "blog/story/..." }`
const wired = new Set(
  [...config.matchAll(/slug:\s*["\']([^"\']+)["\']/g)].map((m) => m[1]),
);

// Autogenerated groups: `autogenerate: { directory: "blog/fronts/exemplar" }`
const autoDirs = [
  ...config.matchAll(/autogenerate:\s*\{\s*directory:\s*["\']([^"\']+)["\']/g),
].map((m) => m[1].replace(/\/+$/, ""));

const covered = (slug) =>
  wired.has(slug) || autoDirs.some((d) => slug === d || slug.startsWith(`${d}/`));

const posts = await discoverPosts();
const missing = posts.filter((p) => !covered(p.slug));

if (missing.length) {
  console.error(
    `[check-nav] FAIL — ${missing.length} post(s) built but NOT reachable from the sidebar (${CONFIG}):`,
  );
  for (const m of missing) {
    console.error(`  ${m.file}`);
    if (m.kind === "front") {
      const dir = m.slug.split("/").slice(0, 3).join("/");
      console.error(`    → wire the track:  { label: "…", autogenerate: { directory: "${dir}" } },`);
      console.error(`    → or the one post: { slug: "${m.slug}" },`);
    } else {
      console.error(`    → add to a sidebar group:  { slug: "${m.slug}" },`);
    }
  }
  console.error(
    `[check-nav] a post not in the nav is invisible on the site. Wire it in, then rebuild.`,
  );
  process.exit(1);
}

const story = posts.filter((p) => p.kind === "story").length;
const front = posts.filter((p) => p.kind === "front").length;
console.error(
  `[check-nav] ✓ all ${posts.length} narrative posts are reachable (${story} story, ${front} front${autoDirs.length ? `; ${autoDirs.length} autogenerated group(s)` : ""})`,
);
