#!/usr/bin/env node
//
// check-nav — every narrative post must be reachable from the sidebar nav.
//
// A post file can exist, build, and deploy while being INVISIBLE on the site,
// because it was never added to astro.config.mjs's sidebar `items`. That is
// exactly how series-007-005 and 007-006 shipped unseen: built, reachable by
// direct URL, absent from the nav. This guard makes that unconstructable.
//
// It covers BOTH narrative tracks (see scripts/lib/posts.mjs):
//   - blog/story/**   the trunk, wired post-by-post with `slug:`
//   - blog/fronts/**  the live workstream tracks, which grow weekly and are
//                     wired by `autogenerate: { directory }` so a new post
//                     needs no nav edit (STORY-BRANCHING.md §3.2, §4.2)
//
// So "wired" means EITHER an explicit `slug:` OR coverage by an autogenerate
// directory. Counting only `slug:` would fail every front post the moment the
// first one lands, and the obvious "fix" — hand-listing them — reintroduces the
// drift FM-3 records.
//
// It runs in the postbuild chain, so even the Cloudflare deploy build refuses an
// unlinked post rather than silently shipping it. Built is not linked.

import { readFile, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { discoverPosts } from "./lib/posts.mjs";

const CONFIG = "astro.config.mjs";
const config = await readFile(CONFIG, "utf-8");

// The realizations sidebar is GENERATED (scripts/mirror-realizations.mjs) and
// imported by the config, so its slugs and nested autogenerate directories are
// not in the config's own text. Read it too, or every mirrored arc reads as
// unwired the moment the nav stopped being hand-listed.
const SIDEBAR_FRAGMENTS = ["src/sidebar-realizations.mjs"];
let generated = "";
for (const f of SIDEBAR_FRAGMENTS) {
  if (existsSync(f)) generated += await readFile(f, "utf-8");
}
const configText = config + generated;

// Explicit leaves: `{ slug: "blog/story/..." }`
const wired = new Set(
  [...configText.matchAll(/slug:\s*["\']([^"\']+)["\']/g)].map((m) => m[1]),
);

// Autogenerated groups: `autogenerate: { directory: "blog/fronts/exemplar" }`
const autoDirs = [
  ...configText.matchAll(/autogenerate:\s*\{\s*directory:\s*["\']([^"\']+)["\']/g),
].map((m) => m[1].replace(/\/+$/, ""));

const covered = (slug) =>
  wired.has(slug) || autoDirs.some((d) => slug === d || slug.startsWith(`${d}/`));

const posts = await discoverPosts();
const missing = posts.filter((p) => !covered(p.slug));

if (missing.length) {
  console.error(
    `[check-nav] FAIL — ${missing.length} post(s) built but NOT reachable from the sidebar (${CONFIG}):`,
  );
  for (const m of missing) {
    console.error(`  ${m.file}`);
    if (m.kind === "front") {
      const dir = m.slug.split("/").slice(0, 3).join("/");
      console.error(`    → wire the track:  { label: "…", autogenerate: { directory: "${dir}" } },`);
      console.error(`    → or the one post: { slug: "${m.slug}" },`);
    } else {
      console.error(`    → add to a sidebar group:  { slug: "${m.slug}" },`);
    }
  }
  console.error(
    `[check-nav] a post not in the nav is invisible on the site. Wire it in, then rebuild.`,
  );
  process.exit(1);
}

// ---------------------------------------------------------------------------
// ANY directory landing must sort FIRST inside its own group.
//
// Starlight's `order` is scoped to the DIRECTORY. A landing that carries a
// number meant for some OUTER list competes with its own siblings and loses.
// This has now happened twice, in two different shapes, and both were plausible:
//
//   fronts        landing order 1..4 meaning "which front is this" — one tied
//                 with its own post 001 and lost the alphabetical tiebreak;
//                 three sorted after their 001 outright.
//   realizations  a fragmented arc's landing carried the ARC NUMBER against
//                 chunks ordered 1..N. Arc 300's landing sorted 18th of 18;
//                 arc 170's sorted 170th of 211 — buried mid-list, which reads
//                 as a missing page rather than a misplaced one.
//
// So this walks the content tree rather than any one section's notion of a
// group: every directory holding an index page plus siblings is checked, and the
// index must carry a strictly lower order than all of them.
// ---------------------------------------------------------------------------
const CONTENT = "src/content/docs";
const orderIn = (text) => {
  const m = text.match(/sidebar:\s*\n\s*order:\s*(-?[0-9.]+)/);
  return m ? Number(m[1]) : null;
};

const walk = async (dir) => {
  let out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, e.name);
    if (e.isDirectory()) out = out.concat(await walk(full));
    else if (/\.mdx?$/.test(e.name)) out.push(full);
  }
  return out;
};

const all = await walk(CONTENT);
const byDir = new Map();
for (const f of all) {
  const d = dirname(f);
  if (!byDir.has(d)) byDir.set(d, []);
  byDir.get(d).push(f);
}

const orderBad = [];
for (const [dir, files] of byDir) {
  const landing = files.find((f) => /\/index\.mdx?$/.test(f));
  const siblings = files.filter((f) => f !== landing);
  if (!landing || siblings.length === 0) continue;

  const lo = orderIn(await readFile(landing, "utf-8"));
  if (lo === null) continue; // no declared order — Starlight's own default applies

  for (const f of siblings) {
    const o = orderIn(await readFile(f, "utf-8"));
    if (o === null) continue;
    if (o <= lo) {
      orderBad.push({
        dir: dir.replace(CONTENT + "/", ""),
        why: `${f.split("/").pop()} has order ${o}, the landing has ${lo}`,
      });
    }
  }
}

if (orderBad.length) {
  const shown = orderBad.slice(0, 8);
  console.error(`\n[check-nav] ✗ ${orderBad.length} landing-order problem(s):\n`);
  for (const b of shown) console.error(`  ${b.dir} — ${b.why}`);
  if (orderBad.length > shown.length) console.error(`  … and ${orderBad.length - shown.length} more`);
  console.error(
    `\n[check-nav] a directory's index page must sort FIRST inside its own group.` +
      `\n            Give the landing a strictly lower 'sidebar: order' than its siblings — 0 works.` +
      `\n            Starlight's order is scoped to the DIRECTORY, not to any outer list.`,
  );
  process.exit(1);
}

const story = posts.filter((p) => p.kind === "story").length;
const front = posts.filter((p) => p.kind === "front").length;
console.error(
  `[check-nav] ✓ all ${posts.length} narrative posts are reachable (${story} story, ${front} front${autoDirs.length ? `; ${autoDirs.length} autogenerated group(s)` : ""})`,
);
